Repository rundeck/docs, pull requests merged in 2019-12, with the labels that each got.

#369 Fix typos and clarify wording.
  docs/manual/job-plugins.md
Labels: port-3.2

#377 Update system-requirements.md
  docs/administration/install/system-requirements.md
Labels: port-to-3.2

#371 Fix some links
  docs/manual/03-getting-started.md
  docs/plugins/index.md
Labels: port-to-3.1

#380 several format edit
  docs/.vuepress/config.js
  docs/.vuepress/sidebar-menus/administration.js
  docs/.vuepress/sidebar-menus/upgrading.js
  docs/administration/configuration/license.md
  docs/administration/configuration/system-properties.md
  docs/administration/install/docker.md
  docs/administration/install/index.md
  docs/administration/install/jar.md
  docs/administration/install/linux-deb.md
  docs/administration/install/linux-rpm.md
  docs/administration/install/system-requirements.md
  docs/administration/install/tomcat.md
  docs/enterprise/quickstart.md
  docs/upgrading/upgrading-to-rundeck3.md
  docs/upgrading/upgrading.md
Labels: port-to-3.2
