Repository rundeck/docs, pull requests merged in 2020-06, with the labels that each got.

#499 framework config for jira plugins.
  docs/manual/node-steps/jira.md
  docs/manual/workflow-steps/jira.md
Labels: port-to-3.3

#498 Update job-resume limitations
  docs/manual/execution-lifecycle/job-resume.md
Labels: port-to-3.3

#497 Update ssh-keygen doc to reflect changes in OpenSSH-Client 8+
  docs/administration/projects/node-execution/ssh.md
Labels: port-to-3.3

#527 Enterprise Simplification
  docs/README.md
  docs/enterprise/index.md
  docs/enterprise/quickstart.md
Labels: port-to-3.2

#538 Changed rd-acl hyperlink
  docs/administration/security/authorization.md
Labels: port-to-3.2

#540 Fdevans doc fixes
  docs/.vuepress/theme/layouts/404.vue
Labels: port-to-3.2

#543 3.2.8 Releaes Notes Overview
  docs/history/3_2_x/version-3.2.8.md
Labels: port-to-3.2

#544 Update base release notes page
  docs/history/README.md
Labels: port-to-3.2

#550 Fix mis-spellings and remove Trello reference
  docs/manual/01-introduction.md
Labels: port-to-3.2

#556 Paged job list component documentation.
  docs/administration/configuration/gui-customization.md
  docs/assets/img/configure-default-job-list.png
Labels: enhancement

#564 Move calendars/license apis under incubating
  docs/.vuepress/config.js
  docs/.vuepress/styles/index.styl
  docs/api/rundeck-api.md
Labels: code merged

#565 Update webhook docs with WebhookResponder information.
  docs/api/rundeck-api.md
  docs/developer/16-webhook-plugins.md
  docs/manual/webhooks/run-job.md
  docs/upgrading/upgrading-to-rundeck-3.3.md
Labels: enhancement

#576 Docs for license storage tree pointed to an incorrect property prefix for configuring the storage tree.
  docs/administration/configuration/license.md
Labels: bug
